# -*- coding: utf-8 -*-
"""Copy of Copy of Cloud Computing Assignment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zcRB-yKE-JWmgux6j8UWqlhwHWEBCK6
"""

!pip install boto3
import boto3

access_id_key = "ASIAXJKLR5ZWQRG7XJ6G"
secret_access_key="zPbvpzLOJSWsMU09l4pnoIueXWba9veJxe5Rrtro"
session_token_key = "FwoGZXIvYXdzEAMaDE+TPzeOFg6vOZOVTyLLARR5JimyRnolOL5hPrrSmP3oWirJv6tR7ZiLsw3a4VvZf07abba+cS+Uq+xyAufwOFkHgNKBc6RQDnE/+wm7MZCtj08EaCa9pCQtg51y94bbtaT+OMUGf8Nhc8A8bDSuKbIjSHzzugi0dtw1mTxrCCBKVf1KCmh7TsrvN8SWKFaz6IOWnNgVT35LzcATmAXYeRS37wpGvgM0GvI73VPihbFoPizDxWwCjXxjS/41japd8iFwvObTRrjVS2OUbhplf8UsUSexf4A5ZY5RKL2vg4oGMi2OOStkkT9nShOKpCS3+H0TBZoX9+WgX08UxJdaV8jxI0yTyVpDNksmFdlEsq8="

boto3client = boto3.client('elasticbeanstalk',region_name="us-east-1",
                            aws_access_key_id=access_id_key,
                            aws_secret_access_key=secret_access_key,
                            aws_session_token=session_token_key
                           
                           )




boto3client.create_application_version(
    ApplicationName='myapp1234',
    AutoCreateApplication=True,
    Description='my-app-v1',
    Process=True,
    SourceBundle={
        'S3Bucket': 'tejeshpersonal',
        'S3Key': 'Mysite.war',
    },
    VersionLabel='v1',
)

import time
time.sleep(10)

response = boto3client.create_environment(
    ApplicationName='myapp1234',
    CNAMEPrefix='my-app-link1234',
    EnvironmentName='my-env',
    SolutionStackName='64bit Amazon Linux 2 v4.2.5 running Tomcat 8.5 Corretto 11',
    VersionLabel='v1',
    OptionSettings=[
        {
            'Namespace': 'aws:autoscaling:launchconfiguration',
            'OptionName': 'IamInstanceProfile',
            'Value': 'aws-elasticbeanstalk-ec2-role',
            
            
        },
        {
            'Namespace': 'aws:autoscaling:launchconfiguration',
            'OptionName': 'InstanceType',
            'Value': 't2.micro',
            
        },
        {
            'Namespace': 'aws:autoscaling:launchconfiguration',
            'OptionName': 'EC2KeyName',
            'Value':  'CS351-CG31',
            
        },
        {
            'Namespace': 'aws:autoscaling:launchconfiguration',
            'OptionName': 'ImageId',
            'Value': 'ami-0c2b8ca1dad447f8a',
            
        },
        {
            'Namespace': 'aws:autoscaling:launchconfiguration',
            'OptionName': 'SecurityGroups',
            'Value': "CS351-CG31-SG",
        },
        {
            
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'BreachDuration',
            'Value': '1',
            
            
            
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'Statistic',
            'Value': 'Average',
            
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'Unit',
            'Value': 'Percent',
             
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'EvaluationPeriods',
            'Value': '1',
               
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'Period',
            'Value': '1',
            
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'UpperThreshold',
            'Value': '70',
            
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'UpperBreachScaleIncrement',
            'Value': '1',
            
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'MeasureName',
            'Value': 'CPUUtilization',
            
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'LowerThreshold',
            'Value': '30',
             
        },
        {
            'Namespace': 'aws:autoscaling:trigger',
            'OptionName': 'LowerBreachScaleIncrement',
            'Value': '-1', 
        },
        {
            'Namespace': 'aws:autoscaling:asg',
            'OptionName': 'Availability Zones',
            'Value': 'Any 2',
            
        },
        {
            'Namespace': 'aws:autoscaling:asg',
            'OptionName': 'MaxSize',
            'Value': '3',
            
        },
        {
            'Namespace': 'aws:autoscaling:asg',
            'OptionName': 'MinSize',
            'Value': '1',
        }
        
        
        

        

        
    ]
)

